# Generated by Django 2.2 on 2021-02-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeler_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='faks',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='firma',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='proje_adi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='proje_turu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
